### ISSUE TITLE
Standard attack (LMB) getting blocked

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1]
- Create a character
- Level up some CLs
- Attack a NPC with your left mouse button attack .. the standard attack
- Hold LMB and keep attacking
- Fire off a special while you are holding the LMB /// Death blow the NPC by using the special attack while holding LMB too. kinda a 100% guarantee to trigger it
- You will now recognize that the LMB attack will not work anymore. Only specials work.
- Quick relog doesnt fix the problem.
- attacking some other targets with LMB / specials / RMB can “break” this block somehow. didnt find a “repeatable” way yet but apparently it is possible that “waiting” some time fixes it

**Comment by Josh-Larson** [comment]
These are the command related packets that trigger the bug. At the beginning LMB works fine, by the end it does not:

```
23-12-19 12:53:51.452 IN  2:	CommandQueueEnqueue[objId=3068657 counter=800 name=target target=0 arguments='']
23-12-19 12:53:51.452 OUT 2:	CommandQueueDequeue[objId=3068657 counter=800 timer=0.0 error=SUCCESS action=0]
23-12-19 12:53:54.910 IN  2:	CommandQueueEnqueue[objId=3068657 counter=1073742656 name=rangedshotrifle target=3250511 arguments='a']
23-12-19 12:53:55.485 OUT 2:	CommandTimer[objId=3068657 crc=0x448]
23-12-19 12:53:56.083 IN  2:	CommandQueueEnqueue[objId=3068657 counter=1073742688 name=bh_dm_4 target=3250511 arguments='a']
23-12-19 12:53:56.435 IN  2:	CommandQueueEnqueue[objId=3068657 counter=1073742720 name=rangedshotrifle target=3250511 arguments='a']
23-12-19 12:53:56.484 OUT 2:	CommandTimer[objId=3068657 crc=0x448]
23-12-19 12:53:56.661 IN  2:	CommandQueueEnqueue[objId=3068657 counter=896 name=null target=3250511 arguments='']
23-12-19 12:53:57.839 IN  2:	CommandQueueEnqueue[objId=3068657 counter=896 name=target target=0 arguments='']
23-12-19 12:53:57.840 OUT 2:	CommandQueueDequeue[objId=3068657 counter=896 timer=0.0 error=SUCCESS action=0]
```

**Comment by madsboddum** [comment]
Based on that log, wouldn't a CommandTimer for the last rangedshotrifle be missing?

**Comment by Undercova** [comment]
that bug pops up for melee weapons too ... for all kind of weapons

**Comment by Undercova** [comment]
still top priority bug

**Comment by Undercova** [comment]
Fixed
