### ISSUE TITLE
[Combat] Ability to damage lairs

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1173]
The current combat engine only supports `CreatureObject` all the way through.
Dealing and receiving damage doesn't work for `TangibleObject`, which is what a lair happens to be.

Receiving damage would be enough for now, in the case of lairs.

**Comment by madsboddum** [comment]
I tried looking into this today and I can't come up with a good solution. The solutions were either:

1. Hard to read (add a bunch of `instanceof`-checks to the existing code).
2. Double maintenance work (a copy of the existing `CreatureObject` code, but adapted for `TangibleObject`, meaning you potentially have to do things twice without realizing).
3. Causing me to be refactoring the combat module to use a dedicated model _and_ all the downstream modules that consume the combat intents, which is a surprisingly large chunk of the codebase - XP, loot, cloning, AI, dueling, buffs, mounts, quests...

I liked introcuding a model dedicated to the combat module the best (what's described as point 3 above), as modelling the differences between `CreatureObject` and `TangibleObject` would've been easy if they were behind an interface.
But at the same time it doesn't seem practical if all our features/modules have to be coupled to the same model - `SWGObject`, `TangibleObject`, `CreatureObject`...

Maybe we could use object IDs in our intents instead? That way each module/feature can be isolated from each other.

**Comment by Undercova** [comment]
Working as intended
