### ISSUE TITLE
Looted items have no "Volume" set

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1174]
![image](https://user-images.githubusercontent.com/5865425/212553540-d41cdc30-c16e-4532-991e-02e179c89af2.png)

**Comment by madsboddum** [comment]
I wonder if there's a case for the volume *ever* being 0?
If there is not, we could initialize it to 1 inside `SWGObject`.

Alternatively, we can set the volume here:
`com/projectswg/holocore/services/gameplay/combat/loot/generation/ItemLootGenerator.kt:77`

```kotlin
itemName.endsWith(".iff") -> {
	loot.add(ObjectCreator.createObjectFromTemplate(itemName))
}
```

**Comment by Undercova** [comment]
Working as intended
