### ISSUE TITLE
[Mission] Imperial/Rebel Mission Terminals

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1240]
We have the imperial and rebel missions in the existing destroy mission SDBs.
The "destroy_type" column must be taken into account to make this work.

**Comment by madsboddum** [comment]
This is at a point where normal terminal missions no longer offer factional missions and the factional mission terminals work and also only offer the relevant missions.

There's no restriction on who can use the factional terminal missions, as I'm not quite sure how that works.

**Comment by Undercova** [comment]
Implemented
