### ISSUE TITLE
[Faction] Switching factions resets your faction rank

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1267]
If you're an imperial colonel and you switch to the rebels, you shouldn't be a colonel.

We should add a check here: com.projectswg.holocore.services.gameplay.faction.FactionFlagService#handleTypeChange
... where we check if `target` is a  `CreatureObject` and set faction rank to 0 if this is the case.

**Comment by Undercova** [comment]
Working as intended
