### ISSUE TITLE
[Admin] Server shutdown timer now displays the correct time in broadcasted system messages

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1282]
In this screenshot, a custom server shutdown sequence was scheduled for 5 minutes. But the system messages are way off, until the last few seconds.

![image](https://user-images.githubusercontent.com/4640241/232234379-cad8511b-0792-4023-9d64-c044ef5c3633.png)

**Comment by Undercova** [comment]
![image](https://github.com/ProjectSWGCore/Holocore/assets/5865425/d616b443-ffe6-4985-9226-cfe66b37c379)

**Comment by Undercova** [comment]
Working as intended
