### ISSUE TITLE
[Vehicle] You can double click a vehicle to dismount it again

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1294]
Steps to reproduce:
1. Call out a vehicle
2. Mount it
3. Double click on the vehicle to dismount (radialing works fine)
4. Error message pops up

Expected behaviour is that double-clicking on the vehicle to dismount actually dismounts.

![image](https://user-images.githubusercontent.com/4640241/232325745-148e49ac-63d1-4eb4-b178-6f597ce02e60.png)

**Comment by madsboddum** [comment]
This is likely a side effect of the changes in 3484d6a3455a7d79ce1519e9a5fb96e4f6863b8c, that fixed #1286.

**Comment by Undercova** [comment]
Working as intended now
