### ISSUE TITLE
Players can not change shape anymore

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1314]
A feature from NGE doesn't work anymore although the command still exists in CU

/setPlayerAppearance /appearance/xxxx.sat

check your sku0_client.toc file for what kind of appearances are possible. very few dont work and will crash your client.
you need to have your target locked in. also move mouse across the character

**Comment by madsboddum** [comment]
Managed to replicate this.

I tried:
`/setPlayerAppearance appearance/darth_vader.sat`
... and it doesn't seem to do anything anymore.

I wonder if the strings we can feed the client are different now that we're using a Pub24 CU client instead of the late NGE one.

**Comment by madsboddum** [comment]
Hmm, perhaps our memories are a bit off regarding this command? I searched for "SWG setPlayerAppearance" on Google and found an example where a mobile iff is used instead.

`/setPlayerAppearance object/mobile/shared_darth_vader.iff`

Using this kind of string works.
![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/941bbd87-1bf1-4055-9709-445b09123a5b)
