### ISSUE TITLE
[NPC] Increased XP grants for killing aggressive, pack and killer NPCs

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1380]
Introduced with Publish 17: https://swg.fandom.com/wiki/Publish_17_Notes_for_26_May_2005
> Increased XP grants for killing aggressive, pack and killer NPCs.  NPCs that are aggressive or assist each other will give a 5% bonus XP amount.  NPCs that will perform a deathblow will also give a 5% bonus XP amount

- [ ] Aggressive NPCs **_or_** assisting NPCs grant a 5% XP bonus. If the NPC is both, you don't get 10%!
- [ ] Deathblow NPCs grant a 5% XP bonus.

Max possible accumulated XP bonus from this feature being 10%.

Code pointer: `com.projectswg.holocore.services.gameplay.combat.CombatExperienceService#calculateXpGain`

**Comment by nav-yam** [comment]
Hi, I am new to your repository and this could be my first open-source contribution. Can you please guide me, how to identify if any NPC is aggressive or assisting and anything like that ?

**Comment by madsboddum** [comment]
> Hi, I am new to your repository and this could be my first open-source contribution. Can you please guide me, how to identify if any NPC is aggressive or assisting and anything like that ?

Welcome! Certainly.

# Aggressive
On a CreatureObject, there are OptionFlags. You can use CreatureObject#hasOptionFlags and specify OptionFlag.AGGRESSIVE to check if the CreatureObject has that flag set.
Something like this: `boolean aggressive = corpse.hasOptionFlags(OptionFlag.AGGRESSIVE);`

# Assisting
You can cast the `corpse` to an AIObject get the Spawner that it is attached to.
Once you have that, you can check what the assist radius is. Assisting NPCs will have a radius larger than 0, like so:
`boolean assisting = ((AIObject) corpse).getSpawner().getAssistRadius() > 0;`

If you have any more questions, feel free to post them in here!

**Comment by madsboddum** [comment]
I see that I missed deathblows.
It's very similar to assisting - on the Spawner, you can use isDeathblow()

**Comment by madsboddum** [comment]
Implemented in #1407.
