### ISSUE TITLE
[Quest] Task: comm_player

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1386]
include library.groundquests;
include library.utils;

// ---------------------------------------------------------------------

inherits quest.task.ground.base_task;

// ---------------------------------------------------------------------

const String dataTableColumnCommMessageText             = "COMM_MESSAGE_TEXT";
const String dataTableColumnNPCAppearanceServerTemplate = "NPC_APPEARANCE_SERVER_TEMPLATE";

const String taskType = "comm_player";

// ---------------------------------------------------------------------

//fires when this task is added to the player
trigger OnTaskActivated(int questCrc, int taskId)
{
	groundquests.questOutputDebugInfo(self, questCrc, taskId, taskType, "OnTaskActivated", taskType + " task activated.");
	//instantly complete
	questCompleteTask(questCrc, taskId, self);
	return SCRIPT_CONTINUE;
}

// ---------------------------------------------------------------------

//fires when the task is completed
trigger OnTaskCompleted(int questCrc, int taskId)
{
	groundquests.questOutputDebugInfo(self, questCrc, taskId, taskType, "OnTaskCompleted", taskType + " task completed.");

	//gather data for this task
	String message    = groundquests.getTaskStringDataEntry(questCrc, taskId, dataTableColumnCommMessageText);
	String appearance = groundquests.getTaskStringDataEntry(questCrc, taskId, dataTableColumnNPCAppearanceServerTemplate);

	prose_package pp = new prose_package ();
	pp.stringId      = utils.unpackString(message);

	commPlayer(self, self, pp, appearance);	

	return SCRIPT_CONTINUE;
}

// ---------------------------------------------------------------------

//fires when the task is completed
trigger OnTaskFailed(int questCrc, int taskId)
{
	groundquests.questOutputDebugInfo(self, questCrc, taskId, taskType, "OnTaskFailed", taskType + " task failed.");
	return SCRIPT_CONTINUE;
}

// ---------------------------------------------------------------------

//fires when the task is cleared
trigger OnTaskCleared(int questCrc, int taskId)
{
	groundquests.questOutputDebugInfo(self, questCrc, taskId, taskType, "OnTaskCleared", taskType + " task cleared.");
	return SCRIPT_CONTINUE;
}

// ---------------------------------------------------------------------

trigger OnDetach()
{
	//make sure the base objvar is removed
	removeObjVar(self, groundquests.getTaskTypeObjVar(self, taskType));
	return SCRIPT_CONTINUE;
}

// ---------------------------------------------------------------------

**Comment by madsboddum** [comment]
This is semi-implemented. I suspect the packet will cause a client crash.
There's a boolean, 'chronicles', in it at the very top. That's a NGE feature.
Simply deleting the boolean may be enough to make it work.
