### ISSUE TITLE
[Character creation] Character selection not rotating anymore

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1444]
When you select a different character type it does not rotate them anymore
All 6 characters are stuck .. but still respond to your input/selection

https://github.com/ProjectSWGCore/Holocore/assets/5865425/8318a949-cbf4-427f-83db-38287d3f8493

**Comment by 1sudo** [comment]
I've noticed this as well, are you using a 30FPS client?

**Comment by Undercova** [comment]
i think i am using the fps version Obique created some time ago. around 100 fps or so i think

**Comment by madsboddum** [comment]
> I haven't tried it with the original client, but I'm willing to bet it will work correctly with it.

I think it broke around the time we introduced the FPS client mod, yeah.

**Comment by Undercova** [comment]
no changes to the client
but it is gone now *shrug*

**Comment by 1sudo** [comment]
It's definitely inconsistent
