### ISSUE TITLE
[Items] Missing string in skillmod section of static item description

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1446]
![image](https://github.com/ProjectSWGCore/Holocore/assets/5865425/1daab132-09da-491f-9d02-12b669696ffb)

**Comment by madsboddum** [comment]
The weapon appears to be configured with the wrong skill mod name.

![LavaCannonStats](https://github.com/ProjectSWGCore/Holocore/assets/4640241/a394c267-1842-4ff5-8cae-f3d093384619)

![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/22556de3-db71-4a69-b7ec-5d7d328508e0)

By changing our SDB, so "skill_buff_ranged_accuracy" → "ranged_accuracy", should fix the problem.
