### ISSUE TITLE
Ressource Class should be object name

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#1454]
![image](https://github.com/ProjectSWGCore/Holocore/assets/5865425/6271d832-d2ca-4c68-bb6a-af8ac787f912)

The resource name itself should NOT be the one used for the object in inventory or when it gets collected

It should be the higher class. like Copper / Wooly Hide  and so on
Apparently always the class before the last specific class

![image](https://github.com/ProjectSWGCore/Holocore/assets/5865425/6f312625-6dbc-4671-a819-1b366aa5e8d4)
in this case:
- Domesticated Wheat
- Wild Oats

We are also missing the following:
- Resource type
- Resource class

**Comment by madsboddum** [comment]
This also seems to be the case when harvesting resources from creatures. We currently show the full name. 

From live:
![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/e01236df-afb0-40d1-94be-43ecd603138f)

From the emulator:
![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/d7554f7f-3dbf-485f-8b32-9037059689a6)

**Comment by Josh-Larson** [comment]
Didn't mean to auto-close

**Comment by Undercova** [comment]
Working as intended
