### ISSUE TITLE
[Quest] XP upon quest completion

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1464]
There's a TODO in QuestService:

```
// TODO award XP, load from tier+level matrix: datatables/quest/quest_experience.iff
```

Convert the client datatable to SDB, write a dataloader and use it where the TODO currently is.

**Comment by Undercova** [comment]
there is no such iff in that location
![image](https://github.com/ProjectSWGCore/Holocore/assets/5865425/678369e6-944a-406f-ad1a-aaa06ee496ad)

**Comment by madsboddum** [comment]
I guess it's a NGE thing then?
