### ISSUE TITLE
[Cybernetics] Chance of having cybernetics installed when cloning

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1549]
1. Check if the character already has a cybernetic installed. If it does have one installed anywhere, don't install another part.
2. Install cybernetic on to player (object system _should_ unequip existing items automatically), with a 5% chance of happening when dying on an elite planet (think Dathomir, Kashyyyk...) and cloning off-world. If the player clones somewhere they have not stored their cloning data, install the legs.

Unequipping them with commands and the like should never be possible. Custom permissions may be required to enforce this.

**Comment by madsboddum** [comment]
This

**Comment by madsboddum** [comment]
Requires a bit more research, as to whether we're supposed to even install anything at all...

![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/13dff1b8-5592-4449-81f2-7515d5058a9e)
https://swg.fandom.com/wiki/Cybernetic

**Comment by madsboddum** [comment]
Seems this was completely disabled four days after the CU released.

> Cybernetics
> 
> **Disabled death-penalty cybernetics.**
> CharacterSheet: the cybernetics button should only appear if the player is actually wearing a cybernetic piece

https://swg.fandom.com/wiki/Update_Notes:_May_1,_2005

So it was possible for a very short time in Publish 15, but by Publish 24, it had been disabled for months.
Closing as wontfix.

**Comment by madsboddum** [comment]
Rage of The Wookiees introduced cybernetics and that expansion released on the 5th of May, 2005.
But those update notes are from the 1st of May, 2005.

For that reason, we suspect the update notes say the death penalty cybernetics have been disabled, simply because they had been released too early. Therefore, we're reopening this issue for now.

**Comment by Undercova** [comment]
:)

**Comment by madsboddum** [comment]
After some digging, it seems that this was indeed disabled temporarily post CU launch, until Rage of The Wookiees launched a bit later.

After the launch of Rage of The Wookiees, the "death penalty cybernetics" became a thing again.

**Comment by Undercova** [comment]
We stick to a general chance of 20% ?

OR

use different values for low/high level planets. like 5-10% for planets like Tatooine. and 20% for Dathomir, Mustafar and co.
