### ISSUE TITLE
[Items] Wound Chance on static item weapons is sometimes too low

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#1559]
**Trandoshan Hunting Rifle, example of Wound Chance being too low**
From live: 
![TrandoshanHuntingRifle](https://github.com/ProjectSWGCore/Holocore/assets/4640241/65c57310-c47b-460d-a5d2-5db6cfd9357f)

Ours:
![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/4bf9eb89-09c5-49f6-9423-b801688eb31e)

**Lava Cannon's fine, though**
From live:
![LavaCannonStats](https://github.com/ProjectSWGCore/Holocore/assets/4640241/1f78a430-8e93-4377-83a4-0464c053adae)

Ours:
![image](https://github.com/ProjectSWGCore/Holocore/assets/4640241/590e50f5-73bf-484d-8a90-4e2b140ee8e7)

The problem seems to be the item SDB, where we must multiply the wound chance of **SOME** entries by 10.

**Comment by Undercova** [comment]
Fixed

**Comment by madsboddum** [comment]
Nice!

On 30 Jun 2024, at 21.05, Undercova ***@***.***> wrote:



Fixed
