### ISSUE TITLE
Simplifying clientdata

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#16]
Manual clientdata extraction is a pain. It also breaks our tests on machines that do not have it, such as Continuous Integration apps. We need a way to fix this. Possible solutions:

1. clientdata uncompressed, which is 2.5GB and would require Git LFS
2. clientdata in a zip in which is 1.17GB in size and would not exceed limitations

**Comment by madsboddum** [comment]
Not very problematic anymore. .trn files are being used for reading terrain height. Uploading those files and nothing else might be alright?
