### ISSUE TITLE
Medic is able to buff all kind of NPCs

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#176]
Medics are able to buff aggressive / attackable / invulnerable NPCs which shouldnt happen at all.

**Comment by madsboddum** [comment]
Makes sense that this is an issue. If it's a NPC, buffing should probably only work if grouped with the player.

Fix must be the group check specifically for NPCs and adding automated tests for that.

**Comment by Undercova** [comment]
Still able to do it

**Comment by Undercova** [comment]
also: when you fire off a buff command and you have a NPC/enemy and/or someone with wrong faction standing as target you should buff yourself

**Comment by madsboddum** [comment]
Ahhh, invulnerable NPCs.

**Comment by Undercova** [comment]
> Ahhh, invulnerable NPCs.

every NPC it worked on. invulnerable ... yellow ones ... red ones ...

**Comment by Undercova** [comment]
Working as intended
