### ISSUE TITLE
CommPlayerMessage packet

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#18]
Check [NGECore2 source for this packet](https://github.com/ProjectSWGCore/NGECore2/blob/a83f3626db55c3dbd5382c336400787b93b57e77/src/protocol/swg/CommPlayerMessage.java).

It's needed for faction changes via /pvp, various Officer abilities and quests.

**Comment by madsboddum** [comment]
Was implemented alongside quests.
