### ISSUE TITLE
Tuning

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#191]
Tuning is basically bio-linking for lightsaber crystals.

**Comment by madsboddum** [comment]
More or less done but needs to handle power crystals as well.

**Comment by Undercova** [comment]
sdb created
https://github.com/ProjectSWGCore/Holocore/commit/751b549660f4a474484c11fe06270796300d2fb0

**Comment by madsboddum** [comment]
Power crystals also need to be supported
