### ISSUE TITLE
NPCs climb into mid-air when fighting you at higher position

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#198]
Go to Smuggler Outpust Endor (or anothere spot where you are above the NPCs)
Get on hill top
Attack the NPCs there
NPCs will then start to move old position to same height level about (screenshot)
You can still fight and kill them

![2020-03-29_10h06_34](https://user-images.githubusercontent.com/5865425/77844271-a9c4a200-71a5-11ea-9f96-1a056a4ebf65.jpg)

**Comment by madsboddum** [comment]
Holocore needs to be able to read terrain height for this to be solved.

**Comment by Undercova** [comment]
Created feature ticket
#296
