### ISSUE TITLE
Lair loading

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#23]
**Requirements**

LairDataLoader (see SpecialLineLoader as example)
- Data should be loaded from serverdata/lair/master_lair.msdb
- Must load data into LairInfo objects

LairCreator
- Method that creates a lair object from a given LairInfo
-- Lair object must use a randomly selected template
-- Lair health should scale with the planet it’s supposed to spawn on

- Method that creates a NPC from a given LairInfo
-- NPC ID should be randomly picked
-- NPC should be created using NPCCreator

**Comment by madsboddum** [comment]
LairInfo should probably be an interface.
