### ISSUE TITLE
Chat room packet submission failures upon zoning in

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#248]
Example of an exception that has been raised:
![image](https://user-images.githubusercontent.com/4640241/87247014-5a9f3600-c451-11ea-8acf-0ae7c50bef71.png)

**Comment by madsboddum** [comment]
Update: Happens because deleted characters don't leave the chat rooms.

**Comment by Undercova** [comment]
Working as intended
