### ISSUE TITLE
Dead character has no clone option after server reboot

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#249]
Go into DWB
Get killed
Log out
Shut server down
Boot server up
Log into character

![2020-07-12_15h37_04](https://user-images.githubusercontent.com/5865425/87247732-dac79a80-c455-11ea-822c-a48297f41d68.jpg)

**Comment by madsboddum** [comment]
Looks like the code handles this. Is the SUI window minimized?

**Comment by Undercova** [comment]
just retested it with given settings and it worked fine
