### ISSUE TITLE
Timer on buff/debuff (player) acting randomly

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#254]
- Attack a NPC and get incapped
- Check the timer on the "Weakened" debuff

OR

- Create a medic
- Gain levels until you can buff yourself
- Check the timer on the buff

Sometimes it goes super slow (like pausing a second)
Sometimes it adds 1 or more seconds
So far it seemed to be randomly

Tested it with 2 medic buffs at the same time. they both went up and down in sync. always the same timer/countdown

![timer_broken](https://user-images.githubusercontent.com/5865425/87270160-9bd62b00-c4cf-11ea-940d-1808bfb560fb.gif)

P.S.: Debuffs on NPCs are not affected as far as i could test it

**Comment by madsboddum** [comment]
Could be fixed fairly easily if buff timers continue running even if the player is offline.

**Comment by Undercova** [comment]
> Could be fixed fairly easily if buff timers continue running even if the player is offline.

you mean when you perform the buff right now ... it will end at a fix time nevertheless if a player is online or offline ?

**Comment by madsboddum** [comment]
I just tried it though and it wasn't a huge success. The client displays the buff timer depending on:

1) How much playtime the player has (online)
2) How long the buff lasts when freshly applied

Currently we're updating playtime a lot because we need to track it in order to expire the buffs. But by doing this, we're constantly telling the client "now you've played this amount of time", causing the weird timer issues.

We basically need a "server playtime" where we track playtime without sending to the client.

**Comment by Undercova** [comment]
Tested it again

- Create new character
- Open character sheet
- Check "Time played"
- **Timer works fine**
- Now apply some buffs to your character (medic is best)
- Move mouse over the buff
- Compare the remaining buff timer and the time played timer ... they behave correlated
- **Timer acts randomly**
- Remove buffs by right clicking them
- **Timer works fine again**

**Comment by Undercova** [comment]
![2021-06-08_01h54_43](https://user-images.githubusercontent.com/5865425/121106415-4224d080-c806-11eb-905b-98870e8446e3.gif)
at 4h:24m:6s the buffs got removed and timer runs fine again

**Comment by Undercova** [comment]
the buffs from equipment like heroic jewelry or belt of Bodo Baas do not affect this

**Comment by Undercova** [comment]
problem popping up with every buff/debuff of a player

**Comment by Undercova** [comment]
check the timer on CENTER OF BEING
the timer sometimes kinda stops or even jumps up

**Comment by Undercova** [comment]
Working as intended now
Tested with Burst Run and Center of Being
