### ISSUE TITLE
RLS database now supports multiple items

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#275]
RLS database has only 1 item defined per category
It should be able to define multiple items per category and seperate them with a semicolon. Like the normal loot tables

**Comment by madsboddum** [comment]
The rarity isn't unique, you can expand the groups by reusing the same rarity.

```
rarity	static_item_ids
TEXT KEY	TEXT
RARE	item_color_crystal_02_16
LEGENDARY	item_color_crystal_02_20
EXCEPTIONAL	item_color_crystal_02_29
EXCEPTIONAL	item_color_crystal_02_30
EXCEPTIONAL	item_color_crystal_02_31
```
