### ISSUE TITLE
PvP zones are not limited to the terrain defined in sdb

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#290]
- Create character
- Use CBT and travel to Yavin 4 Exar Kun
- Approach the temple
- System message about PvP zone pops up. You get blocked from entering the area

PvP zones are not limited to the terrain they have in the sdb. These zones work on ALL terrains
https://github.com/ProjectSWGCore/Holocore/blob/quality_assurance/serverdata/nge/gcw/pvp_zones.sdb

**Comment by madsboddum** [comment]
Odd. Maybe we check coordinates and radius but forget to check which terrain we are on?

**Comment by Undercova** [comment]
Highly possible !
Fits to the coordinates of Restuss PvP zone

**Comment by Undercova** [comment]
Tested. Like you said. Was not able to enter the area on different planets
