### ISSUE TITLE
Terrain height

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#296]
- System needs to read the terrain height
- Create multiple layers
- Water level
- Lairs spawn on the ground not in mid-air

**Comment by madsboddum** [comment]
Patch for AI using terrain height when it's more appropriate.

[ai_terrain_height.zip](https://github.com/ProjectSWGCore/Holocore/files/5760384/ai_terrain_height.zip)

**Comment by madsboddum** [comment]
We should probably include the files for this in the git repo somehow so it always works, without extracting clientdata.
