### ISSUE TITLE
Collections do not get stored permanently

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#326]
Click/Activate some collections
Check collections
Shut down server
Boot up server
Check collections

All set to 0 again

**Comment by madsboddum** [comment]
Fields `collectionBadges` and  `collectionBadges2` in `PlayerObjectShared` seem to not be persisted right now.

**Comment by Undercova** [comment]
#360

**Comment by Undercova** [comment]
Tested and works fine now
