### ISSUE TITLE
Conversation: quest NOT active in requirements

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#335]
In order to be able to grant a quest only once (and not spam it) there needs to be a check if the quest is NOT active right now

**Comment by madsboddum** [comment]
Is it not possible to put an active quest requirement on a conversation telling them to go do their job and then put it before the quest giving conversation

**Comment by Undercova** [comment]
too complex ... and the whole conversation (all conversations at all) will become very nested

how about adding a sub function to the existing "active_quest" one ... boolean check true / false ??

like:
			"type": "active_quest",
			"args": {
				"quest": "quest/purvis_kill_warriors",
				"boolean": true

**Comment by Undercova** [comment]
too much nesting. but I guess I can do it via loading order of conversation in the sdb

**Comment by Undercova** [comment]
there needs to be a "blocking" feature for a conversation ... so it gets skipped and the "next" one gets selected

IF quest_xyz is active THEN skip this conversation

**Comment by madsboddum** [comment]
Could we add an (optional) argument to the active_quest requirement, that specifies true/false?

**Comment by Undercova** [comment]
should be enough
also a "common" check if the quest is active. not if a specific task
