### ISSUE TITLE
Heal: Healing 0 damage needs to be skipped/hidden in combat log

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#349]
Healing someone or an NPC with 0 damage should be hidden/skipped in combat log

![2021-03-21_00h07_51](https://user-images.githubusercontent.com/5865425/111888202-ab046580-89da-11eb-8a98-0cb0de58f03b.jpg)

**Comment by Undercova** [comment]
most likely here
https://github.com/ProjectSWGCore/Holocore/blob/cd7cad9b4c045a4d802b8b489b0f5074172e7cb5/src/main/java/com/projectswg/holocore/services/gameplay/combat/command/CombatCommandHeal.java#L196

**Comment by GeneUNCG** [comment]
This should be fixed now with the latest code in the QA branch. @Undercova

**Comment by Undercova** [comment]
Fixed
