### ISSUE TITLE
Use of /createnpc command

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#37]
New admin command to create a NPC on top of you

/createnpc npc_id difficulty combat_level
/createnpc humanoid_imperial_stormtrooper b 90

Difficulty: b = boss /// e = elite /// n = normal
Combat_level: 1-250 possible
NPC should always be set to ATTACKABLE so it does not attack you instantly (that's why the option is not integrated into the command)
NPC should get auto removed after 30 mins (lifetime)

**Comment by madsboddum** [comment]
Partially implemented here: fd4c7833eef9fa3c11ed1c59120b7620c54e8293.

Doesn't work inside buildings (yet).
