### ISSUE TITLE
Combat XP

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#372]
Combat XP is like 10% of any weapon XP

**Comment by madsboddum** [comment]
Did only Marksman get combat XP? I think everyone gets Combat XP right now.

**Comment by Undercova** [comment]
yeah correct. just checked it again. 10% of the weapon XP

**Comment by madsboddum** [comment]
So the problems with this is that the Trapping XP is also giving Combat XP, causing Combat XP to be granted twice.
Once at 10% for weapon and again at 100% for the trapping XP.

**Comment by madsboddum** [comment]
Oh, and only a marksman should be earning it.

**Comment by Undercova** [comment]
Working as intended
