### ISSUE TITLE
Cash loot

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#374]
Atm the NPCs do not drop any cash and/or the looting itself is not working

**Comment by madsboddum** [comment]
There's probably an error in the log when credits are supposed to be dropped.
It's likely that the credit object doesn't exist pre-NGE.

**Comment by Undercova** [comment]
object/tangible/item/shared_loot_credit_chip.iff

**Comment by Undercova** [comment]
Fixed
https://github.com/ProjectSWGCore/Holocore/commit/e5d97859dcc166f9739d5c895adb0702204455ee
