### ISSUE TITLE
Travel - SWGPacket DataTransform has invalid array length

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#383]
Buy a ticket and travel from Mos Eisley to Anchorhead
All works fine but this pops up in your console

![image](https://user-images.githubusercontent.com/5865425/149262007-7cfb8f8b-40d5-4c83-bc1f-aa554a51acf1.png)

**Comment by madsboddum** [comment]
I also experienced this when teleporting using /teleport admin command.

**Comment by GeneUNCG** [comment]
Does this happen when traveling/teleporting anywhere? If so, what is the error output? May just need to correct the buffer length in DataTransform.
