### ISSUE TITLE
Combat level increases when learning a skill

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#385]
The NGE style is still active, where gaining combat XP will increase your level instantly.
This should happen when learning a combat-related skill instead.

**Comment by Undercova** [comment]
This commit contains the info needed
https://github.com/ProjectSWGCore/Holocore/commit/cc0e0a82632262900d7e9ccb7a110ef676be9fd5

- only combat related xp (see xp_type column) count into CL calculation
- some xp has diifferent multiplier (see column)
- only learned boxes count
- health needs to be added to basic health too
- unlearning a box can result in a CL decrease
