### ISSUE TITLE
ArmorLevel

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#386]
Armor levels

none           = -1
basic           = 0
standard     = 1
advanced    = 2
max             = 3

**Comment by madsboddum** [comment]
Is this a Pre-CU thing?

**Comment by Undercova** [comment]
for crafting
![image](https://user-images.githubusercontent.com/5865425/163405143-81d45f99-7cbb-435c-a19a-ab71b7b75109.png)
