### ISSUE TITLE
Radial "Loot" option not working

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#420]
The double appearance of "Loot" button is gone but the existing one has no function. A double click on target/corpse doesnt work neither. Only the /loot command works and removes all items from the corpse

**Comment by madsboddum** [comment]
Is there a NPC somewhere that usually drops loot? I had trouble finding one at the time, so it was a shot in the dark.

**Comment by Undercova** [comment]
try the Tusken spot east of starport

**Comment by Undercova** [comment]
Working as intended
