### ISSUE TITLE
Creating waypoints for specific coordinates doesnt apply correct coordinates

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#48]
/waypoint 0 0 0

You will then see how the new waypoint will be created at a different spot

Your current X coordinate / your current Z coordinate / new Y coordinate

Example:
- You are at "3518 4 -4802"
- /waypoint 0 0 0
- New waypoint will be created at "3518 4 0"

![2019-01-08_18h12_27](https://user-images.githubusercontent.com/5865425/67169739-83583a80-f3ad-11e9-8e7f-ffee071afefe.jpg)

**Comment by Josh-Larson** [comment]
Fixed in PR: https://github.com/ProjectSWGCore/Holocore/pull/226

**Comment by Undercova** [comment]
Working as intended
