### ISSUE TITLE
Equipped melee and ranged weapons flaw

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#487]
- Equip a ranged weapon
- Get some distance to a NPC, like 30m
- Perform the command "melee hit" (shows as not usable / red cross)
- NPC gets hit

![2022-04-15_17h35_08](https://user-images.githubusercontent.com/5865425/163590511-6336b5d6-0ee9-4377-af2f-589cee15ed63.jpg)

Also:
- Melee weapon equipped
- Target NPC
- Get into 5m range
- Perform command "ranged hit" (shows as not usable / red cross)
- NPC gets hit

**Comment by madsboddum** [comment]
The information appears to be in the "validWeapon" column in the command SDBs.

**Comment by Undercova** [comment]
links to https://discord.com/channels/373548910225915905/373845822871437312/992040236307722250
