### ISSUE TITLE
NPCs don't necessarily spawn on the ground

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#498]
Problem is this: com/projectswg/holocore/resources/support/npc/spawn/NPCCreator.java:169

It should be calculating a height coordinate based on `offsetX` and `offsetZ`, but it's just putting in 0 every time.

```java
builder.translatePosition(offsetX, 0, offsetZ);
```

Check this for inspiration on solving: com.projectswg.holocore.services.support.npc.spawn.DynamicSpawnService#getEggY

**Comment by Undercova** [comment]
check for the slope/steepness of terrain would be good.
system should prefer relatively flat area as spawn spot like housing placement

**Comment by Undercova** [comment]
Fixed
