### ISSUE TITLE
(Un)mounting a vehicle throws an error

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#508]
25-04-22 02:35:14.051 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
25-04-22 02:35:14.051 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
25-04-22 02:35:14.051 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
25-04-22 02:35:14.052 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
25-04-22 02:35:14.052 E:     me.joshlarson.jlcommon/me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
25-04-22 02:35:14.052 E:     java.base/java.lang.Thread.run(Thread.java:835)
25-04-22 02:35:14.052 E:   Exception in thread "intent-processor-0" java.lang.reflect.InvocationTargetException: null
25-04-22 02:35:14.052 E:   Caused by: java.lang.reflect.InvocationTargetException: null
25-04-22 02:35:14.052 E:       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25-04-22 02:35:14.052 E:       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25-04-22 02:35:14.052 E:       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25-04-22 02:35:14.052 E:       java.base/java.lang.reflect.Method.invoke(Method.java:567)
25-04-22 02:35:14.052 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.invoke(Service.java:133)
25-04-22 02:35:14.052 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
25-04-22 02:35:14.052 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
25-04-22 02:35:14.053 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
25-04-22 02:35:14.053 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
25-04-22 02:35:14.053 E:       me.joshlarson.jlcommon/me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
25-04-22 02:35:14.053 E:       java.base/java.lang.Thread.run(Thread.java:835)
25-04-22 02:35:14.053 E:     Exception in thread "intent-processor-0" java.lang.NullPointerException: No known buff: vehicle_3
25-04-22 02:35:14.054 E:     Caused by: java.lang.NullPointerException: No known buff: vehicle_3
25-04-22 02:35:14.054 E:         java.base/java.util.Objects.requireNonNull(Objects.java:246)
25-04-22 02:35:14.054 E:         holocore/com.projectswg.holocore.services.gameplay.combat.buffs.BuffService.handleBuffIntent(BuffService.java:99)
25-04-22 02:35:14.054 E:         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25-04-22 02:35:14.054 E:         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25-04-22 02:35:14.054 E:         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25-04-22 02:35:14.054 E:         java.base/java.lang.reflect.Method.invoke(Method.java:567)
25-04-22 02:35:14.054 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.invoke(Service.java:133)
25-04-22 02:35:14.054 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.Service.lambda$registerIntentHandlers$1(Service.java:119)
25-04-22 02:35:14.054 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentRunner.broadcast(IntentManager.java:214)
25-04-22 02:35:14.055 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.control.IntentManager$IntentExecutor.run(IntentManager.java:269)
25-04-22 02:35:14.055 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.utilities.ThreadUtilities.safeRun(ThreadUtilities.java:47)
25-04-22 02:35:14.055 E:         me.joshlarson.jlcommon/me.joshlarson.jlcommon.concurrency.ThreadPool$ThreadExecutor.threadExecutor(ThreadPool.java:174)
25-04-22 02:35:14.055 E:         java.base/java.lang.Thread.run(Thread.java:835)

**Comment by madsboddum** [comment]
NGE feature with vehicle buffs that needs removal.
