### ISSUE TITLE
Novice elite profession can not be learned

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#525]
Meet the requirements to learn a novice elite skill
Train it
System says you learned it
XP gets deducted
Novice skill box not achieved

**Comment by madsboddum** [comment]
There's probably an error in the log that explains why SkillService won't give you the skill

**Comment by madsboddum** [comment]
Just tried becoming a novice pikeman. This appeared in the log:

01-07-22 16:32:59.522 E: [SkillService] user/Gadoxe Rhodop lacks required skill combat_polearm before being granted skill combat_polearm_novice
