### ISSUE TITLE
Quest datatable parsing

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#56]
See datatables/questtask/quest/axkva_min_intro.iff for an example of a quest file.

Core2 had at least partial support for some of these columns: https://github.com/ProjectSWGCore/NGECore2/blob/a83f3626db55c3dbd5382c336400787b93b57e77/src/services/quest/QuestService.java

**Comment by madsboddum** [comment]
Already implemented. IFF datatables turned into SDB files.
