### ISSUE TITLE
Global cooldown should prevent ability execution

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#568]
Executing an ability will cause that to go on a long cooldown. You cannot use this until it's cooled down.
The other abilities go on a shorter cooldown. The server doesn't block the player from executing an ability that's on the global cooldown.

What's supposed to happen is that the command is enqueued for later. If yet another command is enqueued here, this will replace the existing command in the queue.
It's basically a queue where there's either a command inside or there isn't.

**Comment by Undercova** [comment]
Fixed
