### ISSUE TITLE
Set Bonus Object Attributes

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#58]
We need a link between an item_name and a set bonus set_id.

The object attributes must be applied. The StaticItemService can do that.

- Static items have an additional column assigning the set_id to them => “worn_item_buff”
- the set ids are written down in this table including the count number and linked buff
- https://bitbucket.org/projectswg/holocore/src/quality_assurance/serverdata/items/items_bonus_sets.sdb
- Jedi robes have this id set too => robe + belt
- just need to check if the equipped items have a set_id set. count them … and then grant the linked buff

**Comment by madsboddum** [comment]
Seems to work as intended.
