### ISSUE TITLE
Cloner window shows no city names

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#601]
![image](https://user-images.githubusercontent.com/5865425/177218048-550dc865-d58b-451b-9c45-ab9bc9fe8944.png)

**Comment by madsboddum** [comment]
Example:
![Cloning window](https://user-images.githubusercontent.com/4640241/177231697-31dba320-6c96-4958-bb77-8e8baf87fa81.jpg)

**Comment by Undercova** [comment]
could simply show the town names ... and the distance to cloner in general => Coronet [1038m]
maybe sort it by distance too

**Comment by Undercova** [comment]
Working as intended now
![image](https://user-images.githubusercontent.com/5865425/178862586-72dbedc2-2a84-453a-9a26-84eec3a947cd.png)
