### ISSUE TITLE
(Out of Range) despite being inside range when using long range weapons

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#621]
![image](https://user-images.githubusercontent.com/4640241/177655327-a6231a30-a340-4948-92d0-32438e0a9c07.png)

Despite range on my weapon being valid. Attacks work fine - it's a client issue, likely a delta we're not sending or something.

![image](https://user-images.githubusercontent.com/4640241/177655372-e84e6c7c-79c7-40b6-911a-a5031ea644ce.png)

**Comment by Undercova** [comment]
Working as intended
