### ISSUE TITLE
Parry

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#67]
Only a single target attack can be parried.
Only melee weapons can parry.
Only lightsabers can parry ranged attacks.

**Comment by madsboddum** [comment]
It’s more or less done. Problem is that there’s no flytext for this like there happened to be for dodge. There are two possible solutions:
1. Don’t display flytext for dodge
2. Add client string flytext for parry and publish it (requires game update)

**Comment by Undercova** [comment]
float getParryChance(attacker_data attackerData, defender_data defenderData, combat_data actionData)
{
	float parryChance = 0.0f;

	parryChance += defenderData.parryChance;
	parryChance -= attackerData.reduceParry;
	parryChance -= actionData.reduceParry;

	return parryChance;
}

float getDefenderParryChance(obj_id player)
{
	float parrySkill = isPlayer(player) || beast_lib.isBeast(player) ? 5.0f : (float)getLevel(player) * 0.09f;

	parrySkill += (getDiminishedReturnValue((float)getEnhancedSkillStatisticModifierUncapped(player, "combat_parry"),DR_DEFENDER_PARRY)  / 10.0f);
	parrySkill += ((float)getEnhancedSkillStatisticModifierUncapped(player, "precision_modified") / 200.0f );
	parrySkill += ((float)getSkillStatisticModifier(player, "precision") / 200.0f);
	parrySkill += ((float)getEnhancedSkillStatisticModifierUncapped(player, "agility_modified") / 200.0f);
	parrySkill += ((float)getSkillStatisticModifier(player, "agility") / 200.0f);
	parrySkill += (float)getEnhancedSkillStatisticModifierUncapped(player, "expertise_parry");

	if (beast_lib.isBeastMaster(player) || beast_lib.isBeast(player))
		parrySkill += beast_lib.getBeastParryChance(player);


	parrySkill+= (float)getSkillStatisticModifier(player, "expertise_stance_saber_block");
	boolean isSaberBlocking = buff.hasBuff(player, "saberBlock");

	if (isSaberBlocking)
	{
		float enhancedSaberBlockSkillMod = (float)getSkillStatisticModifier(player, "expertise_saber_block");
		parrySkill += enhancedSaberBlockSkillMod;
	}

	parrySkill = parrySkill > 75.0f ? 75.0f : parrySkill;

	return parrySkill;
}

**Comment by Undercova** [comment]
reduceParry will get its own ticket
