### ISSUE TITLE
Armor Break should also affect innate armor

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#734]
Currently armor break only affects physical armor, but threads on the original forums suggest that innate armor should also be affected.

**Comment by Farsun23** [comment]
For reference:

http://swgforums.swganh.org/viewtopic.php?t=489330 - Focus Thread: Innate Armour vs Battle Armour The Armour Break Debate
http://swgforums.swganh.org/viewtopic.php?t=489505 - TKM innate armor broken
