### ISSUE TITLE
Combat_commands missing area for Force Cost and Force Cost Modifier

### ISSUE THREAD

**Issue by Farsun23** [ProjectSWGCore/Holocore#736]
After a review of the combat_command.sdb in order to implement Jedi-based skills (both offensive, defensive and healing) two additional columns would need to be added:

baseForceCost
fcModifier

Jedi skills generally have a base force cost and then a modifier (such as lightsaber specials, Jedi-based heals, etc.)

**Comment by madsboddum** [comment]
Should be working now.

**Comment by madsboddum** [comment]
Assuming it's working as requested. Closing for now :)
