### ISSUE TITLE
Support for Improved and Advanced versions of abilities

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#738]
It's currently not possible to use Improved or Advanced versions of abilities.
This is because for something like Armor Break, Improved Armor Break and Advanced Armor Break, "armorBreak" is sent regardless of which one you execute.

This means we'll need to do some magic behind the scenes, in order to hit "armorBreak", "armorBreak_1" and "armorBreak_2" in the combat commands SDB.

**Comment by Farsun23** [comment]
As a note, I have tested that improved/advanced levels of buffs do work. For instance, I tested this with forceAura and forceAura_1 both an ability and something that can be found within buff.sdb. I placed the forceAura_1 buff in the forceAura basic skill and when I triggered in-game, I received the forceAura_1 (Improved Force Aura) buff in-game.

**Comment by madsboddum** [comment]
This should work now. An example for Armor Break and stronger versions have been included to demonstrate how it works.
