### ISSUE TITLE
[Combat] Improper Experience Type

### ISSUE THREAD

**Issue by Farsun23** [ProjectSWGCore/Holocore#739]
While testing abilities, I killed a Mos Eisley Police Officer mob as a Jedi utilizing my one-handed lightsaber, this is incorrect during the CU Jedi experience changed from One-handed, Two-handed and Polearm specific experience to a general "Jedi Experience" this is evidenced by the fact that only "Jedi Experience" appears within the Jedi skill trees.

![PSWGimproperexperiencetype](https://user-images.githubusercontent.com/14864277/186094549-5b52198a-db4c-45c9-beb8-17eefa1d81c5.jpg)

**Comment by madsboddum** [comment]
Makes sense, good find.

**Comment by madsboddum** [comment]
This should work now

**Comment by Farsun23** [comment]
This appears to be fixed after commit.

**Comment by madsboddum** [comment]
Great, thank you.
