### ISSUE TITLE
[General] Waypoint names

### ISSUE THREAD

**Issue by Farsun23** [ProjectSWGCore/Holocore#749]
When utilizing /waypoint (or /way) if you have something targeted the name of the waypoint will be that target. Alternatively if you go into your datapad and right click, bring up the radial and then use "Set name" you would be able to set the name of the waypoint, this is currently not functional.

**Comment by Farsun23** [comment]
This appears to be semi-functional in that if you log out and log back in, it appears in the datapad. It should update instantaneously w/o relog.

**Comment by Undercova** [comment]
Used to work fine
Apparently something changed in code and it now requires a relog to update
