### ISSUE TITLE
[General] Effect on corpse

### ISSUE THREAD

**Issue by Farsun23** [ProjectSWGCore/Holocore#751]
Whenever you kill a mob, the mob produces a white light effect on the corpse, this was not present in CU. This would need to be removed.

![screenShot0004](https://user-images.githubusercontent.com/14864277/187126266-1e35ca4e-7a1f-4bb4-94f4-dfd94f8968fb.jpg)

**Comment by Undercova** [comment]
Implemented this to have a visual notification of loot in a NPC corpse like it was in NGE (yellow loot disc)

Question is do we want to remove it at all ? or replace it with a more subtile one ?

**Comment by madsboddum** [comment]
I don't mind removing it.

It's one of those "bug or feature" situations.
We could receive more reports like this from players who think that it shouldn't be there.

**Comment by Farsun23** [comment]
I would be of the mind that since we're pushing for Publish 24 emulation, its done to emulate Publish 24 and then proceed from there.
