### ISSUE TITLE
[Combat] Infinite aggro tether

### ISSUE THREAD

**Issue by Farsun23** [ProjectSWGCore/Holocore#753]
When engaging in combat and attempting to run away it would appear that mobs are not properly tethering and dropping aggro.

Steps to reproduce:
1. Engage in combat with mob;
2. Attempt to run away; 
3. Run several m away and mobs do not drop aggro.

**Comment by Undercova** [comment]
Used to work fine.
NPCs chased/followed you up to a certain distance from their spawner
just checked and the NPC keeps following me (i am walking)

different when i "run" outside awareness range of NPC
