### ISSUE TITLE
Kinetic damage

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#84]
One of the two main weapon damage types, kinetic damage is dealt by most melee weapons, along with a few high-level ranged weapons. Assault armor is extra resistant to kinetic damage, while Reconnaissance armor will usually have lower protection. Personal shield generators will not resist any amount of kinetic damage.

When choosing a weapon for a particular situation, the type of damage it will deliver is of importance. Since armor cannot be changed while in combat, switching damage types can be an effective way to improve your chances.

Other than having different protection values, there is no difference in effects between the two main damage types.

**Comment by madsboddum** [comment]
Unsure what feature this and #82 is for
