### ISSUE TITLE
[Medic] Healing Efficiency should increase healing done

### ISSUE THREAD

**Issue by madsboddum** [ProjectSWGCore/Holocore#919]
We can probably adapt the old NGE Healing Potency code to just read Healing Efficiency instead.

com.projectswg.holocore.services.gameplay.combat.command.CombatCommandHeal#handle

**Comment by Undercova** [comment]
Working as intended

**Comment by Undercova** [comment]
https://github.com/ProjectSWGCore/Holocore/issues/1030
