### ISSUE TITLE
Not able to equip armor items

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#924]
Pick any armor item from CBT
When you try to equip it the error "You lack the skill to use this item" pops up

Even freshly created static items do not work.

Tested on Master TKA and Novice Medic (CL54)

**Comment by madsboddum** [comment]
TKAs do not get armor certification, so this is expected behavior I believe.

Try Pikeman instead - notice the armor stuff that the Novice skill box grants you.
